services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fastapi-db
          property: connectionString
      - key: PORT
        value: 8000

databases:
  - name: fastapi-db
    plan: free
    databaseName: fastapi
    user: fastapi
